name: cicd
on: push
jobs: 
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  

      - name: extract version from pom.xml
        id: extract_version
        run: |
          VERSION= VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION"
          echo "::set-output name=VERSION::$VERSION"

      - name: Run Maven Test
        run: mvn clean test

      - name: Build Jar
        run: mvn package -DskipTests
        
      - name: login into DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/eks-app:${{ steps.extract_version.outputs.VERSION }} .
         
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/eks-app:${{ steps.extract_version.outputs.VERSION }}

      - name: show pushed image
        run: |
          echo ${{ secrets.DOCKER_HUB_USERNAME }}/eks-app:${{ steps.extract_version.outputs.VERSION }}