name: Test Ephemeral Runner

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, eks-ephemeral]

    steps:
      - uses: actions/checkout@v4

      - name: Show environment
        run: |
          echo "Running inside EKS ephemeral runner"
          hostname
          uname -a

      - name: Sleep demo
        run: sleep 20
