name: Build & Test Maven App (Ephemeral Runner)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, eks-ephemeral]

    steps:
      - uses: actions/checkout@v4

      - name: Show environment
        run: |
          echo "Running inside EKS ephemeral runner"
          hostname
          uname -a

      - name: Install Maven (Amazon Linux)
        run: |
          sudo yum update -y
          sudo yum install -y maven
          mvn -v

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Resolve dependencies
        run: mvn dependency:resolve --batch-mode

      - name: Run tests
        run: mvn test --batch-mode

      - name: Build JAR
        run: mvn clean package --batch-mode

      - name: Extract version
        id: jarver
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Project version: $VERSION"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ steps.jarver.outputs.version }}
          path: target/*.jar
